apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: lint
    agent: tekton-pipeline
    context: "lint"
    alwaysRun: true
    optional: false
    trigger: "/lint"
    rerunCommand: "/relint"
    sourcePath: "lint.yaml"
