apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: test
    context: "test"
    alwaysRun: true
    optional: false
    trigger: "/test"
    rerunCommand: "/retest"
    sourcePath: "test.yaml"
  postsubmits:
  - name: release
    context: "release"
    sourcePath: "release.yaml"

